"""Source of truth for 200-lesson math / algorithm directory names.

Lesson dirs:
  project/curriculum_math_200/{A|B}{cc}_{chapter}/{nnn}_{slug}/
  project/curriculum_algorithm_200/D{cc}_{chapter}/{nnn}_{slug}/
"""

from __future__ import annotations

MATH_CHAPTERS: list[tuple[str, str, str, int, int]] = [
    ("A01", "algebra", "数と式", 1, 10),
    ("A02", "sets_logic", "集合と論理", 11, 16),
    ("A03", "quadratic", "二次関数", 17, 24),
    ("A04", "analytic_geometry", "図形と方程式", 25, 32),
    ("A05", "trigonometry", "三角比・三角関数", 33, 44),
    ("A06", "exp_log", "指数・対数関数", 45, 52),
    ("A07", "sequences", "数列", 53, 64),
    ("A08", "probability", "場合の数・確率", 65, 74),
    ("A09", "geometry", "平面図形・空間図形", 75, 82),
    ("A10", "integers", "整数の性質", 83, 88),
    ("A11", "vectors", "ベクトル", 89, 98),
    ("A12", "complex", "複素数平面", 99, 104),
    ("A13", "calculus", "極限・微分・積分", 105, 116),
    ("A14", "applications", "数学と社会・総合演習", 117, 120),
    ("B01", "analysis", "微分積分学", 121, 128),
    ("B02", "multivariable", "多変数の微分積分", 129, 136),
    ("B03", "linear_algebra", "線形代数", 137, 150),
    ("B04", "ode", "常微分方程式", 151, 156),
    ("B05", "probability_stats", "確率論・統計学", 157, 168),
    ("B06", "topology", "集合・位相・論理", 169, 174),
    ("B07", "number_theory", "数論・離散数学", 175, 180),
    ("B08", "complex_analysis", "複素解析入門", 181, 186),
    ("B09", "abstract_algebra", "代数学入門", 187, 192),
    ("B10", "advanced", "総合・発展トピック", 193, 200),
]

ALGO_CHAPTERS: list[tuple[str, str, str, int, int]] = [
    ("D01", "complexity", "導入・計算量", 1, 10),
    ("D02", "data_structures", "基本データ構造", 11, 24),
    ("D03", "advanced_ds", "高度なデータ構造", 25, 34),
    ("D04", "sorting", "ソートアルゴリズム", 35, 46),
    ("D05", "search", "探索アルゴリズム", 47, 56),
    ("D06", "divide_and_conquer", "再帰・分割統治法", 57, 66),
    ("D07", "graphs", "グラフ理論の基礎", 67, 76),
    ("D08", "shortest_paths", "最短路・最小全域木", 77, 88),
    ("D09", "advanced_graphs", "高度なグラフアルゴリズム", 89, 100),
    ("D10", "dp", "動的計画法", 101, 114),
    ("D11", "greedy", "貪欲法・設計技法", 115, 124),
    ("D12", "strings", "文字列アルゴリズム", 125, 136),
    ("D13", "number_theory", "数論アルゴリズム", 137, 146),
    ("D14", "computational_geometry", "計算幾何学", 147, 156),
    ("D15", "complexity_theory", "NP完全性・計算複雑性", 157, 166),
    ("D16", "randomized", "ランダム化アルゴリズム", 167, 174),
    ("D17", "parallel", "並列・分散アルゴリズム", 175, 182),
    ("D18", "ml_algorithms", "機械学習の基礎アルゴリズム", 183, 192),
    ("D19", "game_theory", "オンライン・ゲーム理論", 193, 196),
    ("D20", "wrap_up", "総合演習・まとめ", 197, 200),
]

# (number, japanese title, english slug)
MATH_LESSONS: list[tuple[int, str, str]] = [
    (1, "整式の展開と因数分解", "expand_and_factor"),
    (2, "因数分解の応用（複雑な式）", "factoring_advanced"),
    (3, "平方根と分母の有理化", "square_roots_rationalize"),
    (4, "絶対値を含む方程式・不等式", "absolute_value_eq_ineq"),
    (5, "多項式の割り算", "polynomial_division"),
    (6, "剰余の定理と因数定理", "remainder_factor_theorem"),
    (7, "恒等式と係数比較", "identities_coefficients"),
    (8, "部分分数分解", "partial_fractions"),
    (9, "相加平均・相乗平均の関係", "am_gm"),
    (10, "不等式の証明技法", "inequality_proofs"),
    (11, "集合の基本演算（和集合・共通部分・補集合）", "set_operations"),
    (12, "ド・モルガンの法則", "de_morgan"),
    (13, "命題と条件", "propositions"),
    (14, "必要条件・十分条件", "necessary_sufficient"),
    (15, "対偶と背理法", "contrapositive_contradiction"),
    (16, "数学的帰納法の基本", "mathematical_induction"),
    (17, "二次関数の平行移動と頂点", "quadratic_shift_vertex"),
    (18, "二次関数の最大値・最小値", "quadratic_max_min"),
    (19, "二次方程式と判別式", "quadratic_discriminant"),
    (20, "二次不等式の解き方", "quadratic_inequalities"),
    (21, "解と係数の関係", "vieta_formulas"),
    (22, "二次関数と二次方程式の融合問題", "quadratic_mixed"),
    (23, "放物線と直線の共有点", "parabola_line"),
    (24, "二次関数の応用（最適化問題）", "quadratic_optimization"),
    (25, "直線の方程式と傾き", "line_equation_slope"),
    (26, "円の方程式", "circle_equation"),
    (27, "点と直線の距離", "point_line_distance"),
    (28, "二直線の位置関係（平行・垂直）", "parallel_perpendicular"),
    (29, "円と直線の位置関係", "circle_and_line"),
    (30, "軌跡と方程式", "locus"),
    (31, "不等式の表す領域", "inequality_regions"),
    (32, "領域における最大・最小（線形計画法）", "linear_programming"),
    (33, "三角比の定義（sin, cos, tan）", "trig_ratios"),
    (34, "正弦定理", "law_of_sines"),
    (35, "余弦定理", "law_of_cosines"),
    (36, "三角形の面積公式", "triangle_area"),
    (37, "弧度法と単位円", "radians_unit_circle"),
    (38, "三角関数のグラフ", "trig_graphs"),
    (39, "加法定理", "addition_formulas"),
    (40, "三角関数の合成", "trig_synthesis"),
    (41, "積和公式・和積公式", "product_sum_formulas"),
    (42, "三角方程式・三角不等式", "trig_eq_ineq"),
    (43, "三角関数の最大・最小", "trig_max_min"),
    (44, "三角関数の応用（周期現象のモデル化）", "trig_periodic_models"),
    (45, "指数法則と指数関数", "exponential_laws"),
    (46, "対数の定義と性質", "log_definition"),
    (47, "対数関数のグラフ", "log_graphs"),
    (48, "指数方程式・対数方程式", "exp_log_equations"),
    (49, "指数不等式・対数不等式", "exp_log_inequalities"),
    (50, "常用対数と桁数の問題", "common_log_digits"),
    (51, "指数関数的な増加・減少モデル", "exponential_growth"),
    (52, "ネイピア数 e の直感的な導入", "napier_e"),
    (53, "等差数列", "arithmetic_sequence"),
    (54, "等比数列", "geometric_sequence"),
    (55, "数列の和（シグマ記号）", "sequence_sums_sigma"),
    (56, "シグマ公式の導出", "sigma_formulas"),
    (57, "階差数列", "difference_sequence"),
    (58, "漸化式の基本", "recurrence"),
    (59, "連立漸化式", "simultaneous_recurrence"),
    (60, "数学的帰納法による証明（数列）", "induction_sequences"),
    (61, "無限級数の基礎", "infinite_series_intro"),
    (62, "群数列", "grouped_sequences"),
    (63, "漸化式と数列の応用問題", "recurrence_applications"),
    (64, "数列と関数の融合問題", "sequence_function_mixed"),
    (65, "順列", "permutations"),
    (66, "円順列・重複順列", "circular_permutations"),
    (67, "組合せ", "combinations"),
    (68, "二項定理", "binomial_theorem"),
    (69, "確率の基本", "probability_basics"),
    (70, "余事象の確率", "complementary_probability"),
    (71, "条件付き確率", "conditional_probability"),
    (72, "独立な試行の確率", "independent_trials"),
    (73, "期待値", "expected_value"),
    (74, "漸化式を用いた確率の計算", "recurrence_probability"),
    (75, "三角形の重心・内心・外心", "triangle_centers"),
    (76, "円に内接する四角形の性質", "cyclic_quadrilateral"),
    (77, "メネラウスの定理とチェバの定理", "menelaus_ceva"),
    (78, "円と接線・接弦定理", "tangent_chord"),
    (79, "相似と面積比・体積比", "similarity_ratios"),
    (80, "空間図形の基本（多面体）", "polyhedra"),
    (81, "空間図形の切断", "solid_sections"),
    (82, "立体の展開図と最短経路", "nets_shortest_path"),
    (83, "約数と倍数", "divisors_multiples"),
    (84, "ユークリッドの互除法", "euclidean_algorithm"),
    (85, "合同式（mod）の基本", "modular_arithmetic"),
    (86, "一次不定方程式の整数解", "linear_diophantine"),
    (87, "n進法", "base_n"),
    (88, "整数問題の総合演習", "integer_problems"),
    (89, "平面ベクトルの基本演算", "plane_vectors"),
    (90, "ベクトルの内積", "inner_product"),
    (91, "位置ベクトルと図形への応用", "position_vectors"),
    (92, "内分点・外分点とベクトル", "internal_external_division"),
    (93, "空間ベクトルの基本", "space_vectors"),
    (94, "空間における直線・平面の方程式", "lines_planes_space"),
    (95, "法線ベクトルと平面", "normal_vector"),
    (96, "ベクトル方程式", "vector_equations"),
    (97, "ベクトルを用いた図形の証明", "vector_proofs"),
    (98, "空間図形とベクトルの応用", "space_vector_apps"),
    (99, "複素数の四則演算", "complex_arithmetic"),
    (100, "複素数平面と極形式", "complex_polar"),
    (101, "ド・モアブルの定理", "de_moivre"),
    (102, "複素数と図形問題", "complex_geometry"),
    (103, "複素数の回転と拡大", "complex_rotation"),
    (104, "複素数のn乗根", "complex_nth_roots"),
    (105, "数列の極限", "sequence_limits"),
    (106, "関数の極限", "function_limits"),
    (107, "微分係数と導関数の定義", "derivative_definition"),
    (108, "導関数の基本公式（積・商・合成関数）", "derivative_rules"),
    (109, "三角関数・指数関数・対数関数の微分", "trig_exp_log_derivatives"),
    (110, "接線と法線の方程式", "tangent_normal"),
    (111, "関数の増減とグラフの作成", "increase_decrease_graphs"),
    (112, "不定積分の基本", "indefinite_integral"),
    (113, "定積分と面積", "definite_integral_area"),
    (114, "置換積分・部分積分（高校範囲）", "substitution_parts"),
    (115, "回転体の体積", "solids_of_revolution"),
    (116, "微分・積分の応用（速度・近似）", "calc_applications"),
    (117, "統計的な推測の基礎（高校範囲）", "statistical_inference"),
    (118, "データの分析（分散・標準偏差・相関係数）", "data_analysis"),
    (119, "数学的モデリングの考え方", "mathematical_modeling"),
    (120, "高校数学の総合演習（複数分野の融合問題）", "hs_comprehensive"),
    (121, "ε–δ論法と極限の厳密な定義", "epsilon_delta"),
    (122, "連続関数と中間値の定理", "continuity_ivt"),
    (123, "平均値の定理", "mean_value_theorem"),
    (124, "テイラー展開とマクローリン展開", "taylor_maclaurin"),
    (125, "広義積分（収束・発散）", "improper_integrals"),
    (126, "級数の収束判定法", "series_tests"),
    (127, "一様収束", "uniform_convergence"),
    (128, "微分方程式入門（変数分離形）", "separable_ode"),
    (129, "多変数関数と偏微分", "partial_derivatives"),
    (130, "全微分と接平面", "total_differential"),
    (131, "陰関数定理", "implicit_function"),
    (132, "多変数のテイラー展開", "multivariable_taylor"),
    (133, "極値問題とヘッセ行列", "extrema_hessian"),
    (134, "ラグランジュの未定乗数法", "lagrange_multipliers"),
    (135, "重積分（累次積分）", "multiple_integrals"),
    (136, "変数変換とヤコビアン", "jacobian"),
    (137, "ベクトル空間の基本", "vector_spaces"),
    (138, "一次独立・一次従属と基底", "linear_independence_basis"),
    (139, "行列の演算と基本変形", "matrix_operations"),
    (140, "連立一次方程式と掃き出し法", "gaussian_elimination"),
    (141, "行列式の定義と性質", "determinants"),
    (142, "逆行列とその求め方", "inverse_matrix"),
    (143, "一次変換と行列", "linear_transformations"),
    (144, "固有値と固有ベクトル", "eigenvalues"),
    (145, "対角化", "diagonalization"),
    (146, "内積空間と正規直交基底", "inner_product_spaces"),
    (147, "グラム・シュミットの直交化", "gram_schmidt"),
    (148, "対称行列と直交対角化", "orthogonal_diagonalization"),
    (149, "線形写像の階数・次元定理", "rank_nullity"),
    (150, "ジョルダン標準形の直感", "jordan_form"),
    (151, "一階線形微分方程式", "first_order_linear_ode"),
    (152, "二階線形微分方程式（定数係数・斉次）", "second_order_homogeneous"),
    (153, "二階線形微分方程式（非斉次）", "second_order_nonhomogeneous"),
    (154, "連立微分方程式と行列", "systems_of_ode"),
    (155, "ラプラス変換の基礎", "laplace_transform"),
    (156, "微分方程式の応用（振動・減衰）", "ode_oscillation"),
    (157, "確率空間と確率変数", "probability_space"),
    (158, "期待値と分散", "expectation_variance"),
    (159, "二項分布", "binomial_distribution"),
    (160, "ポアソン分布", "poisson_distribution"),
    (161, "正規分布", "normal_distribution"),
    (162, "中心極限定理", "central_limit_theorem"),
    (163, "大数の法則", "law_of_large_numbers"),
    (164, "標本平均と推定", "sample_mean_estimation"),
    (165, "仮説検定の基礎", "hypothesis_testing"),
    (166, "相関と回帰分析", "correlation_regression"),
    (167, "マルコフ連鎖の基礎", "markov_chains"),
    (168, "ベイズ統計の基礎", "bayesian_statistics"),
    (169, "集合論の基礎（濃度・可算集合）", "set_theory_cardinality"),
    (170, "写像と全射・単射・全単射", "maps_injective_surjective"),
    (171, "距離空間の基本", "metric_spaces"),
    (172, "開集合・閉集合", "open_closed_sets"),
    (173, "コンパクト性の直感", "compactness"),
    (174, "論理と証明の技法（数学的帰納法の一般化）", "proof_techniques"),
    (175, "素数と素因数分解", "primes_factorization"),
    (176, "オイラーの定理とフェルマーの小定理", "euler_fermat"),
    (177, "中国剰余定理", "chinese_remainder"),
    (178, "グラフ理論の基礎（大学レベル）", "graph_theory_intro"),
    (179, "組合せ論（鳩の巣原理・包除原理）", "combinatorics_php_pie"),
    (180, "生成関数の基礎", "generating_functions"),
    (181, "複素関数の基礎", "complex_functions"),
    (182, "コーシー・リーマンの方程式", "cauchy_riemann"),
    (183, "コーシーの積分定理", "cauchy_integral"),
    (184, "留数定理入門", "residue_theorem"),
    (185, "等角写像の基礎", "conformal_maps"),
    (186, "複素関数の応用（流体・電磁場のモデル化）", "complex_applications"),
    (187, "群の定義と具体例", "groups"),
    (188, "部分群と巡回群", "subgroups_cyclic"),
    (189, "環と体の基礎", "rings_fields"),
    (190, "剰余環の考え方", "quotient_rings"),
    (191, "準同型写像と同型定理", "homomorphisms"),
    (192, "ガロア理論への入り口", "galois_preview"),
    (193, "フーリエ級数の基礎", "fourier_series"),
    (194, "フーリエ変換の基礎", "fourier_transform"),
    (195, "変分法の初歩", "calculus_of_variations"),
    (196, "測度論の直感（ルベーグ積分入門）", "measure_theory"),
    (197, "位相空間論の初歩（連続写像の一般化）", "topology_intro"),
    (198, "数値解析の基礎（ニュートン法・数値積分）", "numerical_analysis"),
    (199, "最適化理論の基礎（凸関数と最適化）", "convex_optimization"),
    (200, "大学数学の総合演習（複数分野の融合問題）", "university_comprehensive"),
]

ALGO_LESSONS: list[tuple[int, str, str]] = [
    (1, "アルゴリズムとは何か", "what_is_an_algorithm"),
    (2, "計算量とビッグO記法", "big_o"),
    (3, "時間計算量と空間計算量", "time_space_complexity"),
    (4, "最良・最悪・平均計算量", "best_worst_average"),
    (5, "漸近記法（Ω, Θ）の使い分け", "omega_theta"),
    (6, "再帰と計算量の関係", "recursion_complexity"),
    (7, "再帰木による計算量の見積もり", "recursion_tree"),
    (8, "マスター定理", "master_theorem"),
    (9, "償却解析（amortized analysis）の考え方", "amortized_analysis"),
    (10, "P と NP の入門", "p_vs_np_intro"),
    (11, "配列とリスト", "arrays_lists"),
    (12, "連結リスト（単方向・双方向）", "linked_lists"),
    (13, "スタック", "stack"),
    (14, "キュー", "queue"),
    (15, "デック（両端キュー）", "deque"),
    (16, "木構造の基本", "trees"),
    (17, "二分探索木", "bst"),
    (18, "平衡二分探索木（AVL木の直感）", "avl"),
    (19, "赤黒木の直感", "red_black_tree"),
    (20, "ヒープと優先度付きキュー", "heap_priority_queue"),
    (21, "二項ヒープ・フィボナッチヒープの直感", "binomial_fibonacci_heap"),
    (22, "ハッシュテーブル", "hash_table"),
    (23, "Union-Find（素集合データ構造）", "union_find"),
    (24, "セグメント木", "segment_tree"),
    (25, "Fenwick木（Binary Indexed Tree）", "fenwick_tree"),
    (26, "平方分割（区間クエリの高速化）", "sqrt_decomposition"),
    (27, "トライ木（Trie）", "trie"),
    (28, "スキップリスト", "skip_list"),
    (29, "レンジツリー", "range_tree"),
    (30, "パーシステントデータ構造の考え方", "persistent_ds"),
    (31, "スパーステーブル", "sparse_table"),
    (32, "LCAのためのオイラー路+セグメント木", "lca_euler_segtree"),
    (33, "Sqrt Decompositionの応用", "sqrt_decomposition_apps"),
    (34, "データ構造の総合演習", "ds_comprehensive"),
    (35, "バブルソート", "bubble_sort"),
    (36, "選択ソート", "selection_sort"),
    (37, "挿入ソート", "insertion_sort"),
    (38, "マージソート", "merge_sort"),
    (39, "クイックソート", "quick_sort"),
    (40, "ヒープソート", "heap_sort"),
    (41, "計数ソート", "counting_sort"),
    (42, "バケットソート", "bucket_sort"),
    (43, "基数ソート", "radix_sort"),
    (44, "シェルソート", "shell_sort"),
    (45, "外部ソートの考え方", "external_sort"),
    (46, "ソートアルゴリズムの比較と安定性", "sort_comparison"),
    (47, "線形探索", "linear_search"),
    (48, "二分探索", "binary_search"),
    (49, "二分探索の応用（境界探索・下限/上限）", "binary_search_bounds"),
    (50, "三分探索", "ternary_search"),
    (51, "幅優先探索（BFS）", "bfs"),
    (52, "深さ優先探索（DFS）", "dfs"),
    (53, "反復深化探索", "iterative_deepening"),
    (54, "A*探索アルゴリズム", "a_star"),
    (55, "双方向探索", "bidirectional_search"),
    (56, "ジャンプ探索・補間探索", "jump_interpolation_search"),
    (57, "再帰の基本と再帰木", "recursion_basics"),
    (58, "分割統治法の考え方", "divide_and_conquer"),
    (59, "累乗の高速計算（繰り返し二乗法）", "binary_exponentiation"),
    (60, "最大部分配列問題（分割統治法）", "max_subarray"),
    (61, "クイックセレクト", "quickselect"),
    (62, "二分探索とメモ化の融合", "binary_search_memo"),
    (63, "ストラッセンの行列積アルゴリズム入門", "strassen"),
    (64, "高速フーリエ変換（FFT）による多項式乗算", "fft_polynomial"),
    (65, "分割統治法による最近点対問題", "closest_pair"),
    (66, "マンハッタン距離の最近点対", "manhattan_closest_pair"),
    (67, "グラフの表現方法（隣接行列・隣接リスト）", "graph_representation"),
    (68, "グラフの種類（有向・無向・重み付き）", "graph_types"),
    (69, "連結性と連結成分", "connectivity"),
    (70, "木とグラフの関係", "trees_and_graphs"),
    (71, "グラフの走査（BFS/DFSの応用）", "graph_traversal"),
    (72, "トポロジカルソート", "topological_sort"),
    (73, "オイラー路とハミルトン路", "euler_hamilton"),
    (74, "二部グラフ判定", "bipartite_check"),
    (75, "グラフの彩色問題の入門", "graph_coloring"),
    (76, "平面グラフとオイラーの公式", "planar_euler"),
    (77, "ダイクストラ法（最短路問題）", "dijkstra"),
    (78, "ベルマン・フォード法", "bellman_ford"),
    (79, "フロイド・ワーシャル法", "floyd_warshall"),
    (80, "ジョンソンのアルゴリズム", "johnson"),
    (81, "0-1 BFS", "zero_one_bfs"),
    (82, "プリム法（最小全域木）", "prim"),
    (83, "クラスカル法（最小全域木）", "kruskal"),
    (84, "ボルフカ法（最小全域木）", "boruvka"),
    (85, "最小全域木の応用問題", "mst_applications"),
    (86, "負辺のある最短路問題", "negative_edges"),
    (87, "k番目の最短路", "kth_shortest"),
    (88, "最短路問題の総合演習", "shortest_path_comprehensive"),
    (89, "強連結成分分解（Tarjanのアルゴリズム）", "tarjan_scc"),
    (90, "強連結成分分解（Kosarajuのアルゴリズム）", "kosaraju"),
    (91, "木の直径", "tree_diameter"),
    (92, "LCA（最小共通祖先）", "lca"),
    (93, "オイラーツアーテクニック", "euler_tour"),
    (94, "最大流問題とフォード・ファルカーソン法", "ford_fulkerson"),
    (95, "エドモンズ・カープ法", "edmonds_karp"),
    (96, "最小カット問題", "min_cut"),
    (97, "二部マッチング", "bipartite_matching"),
    (98, "ホップクロフト・カープ法", "hopcroft_karp"),
    (99, "一般グラフの最大マッチング入門", "general_matching"),
    (100, "最小費用流問題", "min_cost_flow"),
    (101, "動的計画法の基本的な考え方", "dp_intro"),
    (102, "フィボナッチ数列と記憶化", "fibonacci_memo"),
    (103, "ナップサック問題（0-1）", "knapsack_01"),
    (104, "ナップサック問題（個数無制限）", "knapsack_unbounded"),
    (105, "最長共通部分列（LCS）", "lcs"),
    (106, "最長増加部分列（LIS）", "lis"),
    (107, "編集距離", "edit_distance"),
    (108, "区間DP", "interval_dp"),
    (109, "木DP", "tree_dp"),
    (110, "ビットDP", "bit_dp"),
    (111, "桁DP", "digit_dp"),
    (112, "巡回セールスマン問題とDP", "tsp_dp"),
    (113, "期待値DP", "expected_dp"),
    (114, "動的計画法の総合演習", "dp_comprehensive"),
    (115, "貪欲法の考え方", "greedy"),
    (116, "区間スケジューリング問題", "interval_scheduling"),
    (117, "ハフマン符号", "huffman"),
    (118, "バックトラッキング法", "backtracking"),
    (119, "分枝限定法", "branch_and_bound"),
    (120, "局所探索法", "local_search"),
    (121, "焼きなまし法の直感", "simulated_annealing"),
    (122, "答えで二分探索する最適化テクニック", "binary_search_on_answer"),
    (123, "平衡二分探索木を用いた設計例", "balanced_bst_design"),
    (124, "貪欲法とDPの使い分け", "greedy_vs_dp"),
    (125, "文字列マッチングの基礎（力任せ法）", "naive_string_match"),
    (126, "KMP法", "kmp"),
    (127, "ラビン・カープ法", "rabin_karp"),
    (128, "Zアルゴリズム", "z_algorithm"),
    (129, "接尾辞配列の基礎", "suffix_array"),
    (130, "接尾辞配列の構築（SA-IS等の直感）", "sa_is"),
    (131, "LCP配列", "lcp_array"),
    (132, "接尾辞木の基礎", "suffix_tree"),
    (133, "Aho-Corasick法（複数パターン照合）", "aho_corasick"),
    (134, "マナカーのアルゴリズム（最長回文）", "manacher"),
    (135, "ローリングハッシュの応用", "rolling_hash"),
    (136, "文字列アルゴリズムの総合演習", "strings_comprehensive"),
    (137, "エラトステネスの篩", "sieve_of_eratosthenes"),
    (138, "セグメント篩", "segmented_sieve"),
    (139, "拡張ユークリッドの互除法", "extended_euclidean"),
    (140, "モジュラー逆元", "modular_inverse"),
    (141, "高速な冪乗剰余計算", "modular_exponentiation"),
    (142, "素数判定（フェルマーテスト・ミラー–ラビン法）", "primality_tests"),
    (143, "中国剰余定理のアルゴリズム的実装", "crt_algorithm"),
    (144, "離散対数問題の入門", "discrete_log"),
    (145, "RSA暗号の仕組みの基礎", "rsa_basics"),
    (146, "数論変換（NTT）の直感", "ntt"),
    (147, "点と線分の位置関係", "point_segment"),
    (148, "凸包（Convex Hull）アルゴリズム", "convex_hull"),
    (149, "線分交差判定", "segment_intersection"),
    (150, "多角形の面積計算", "polygon_area"),
    (151, "走査線アルゴリズムの考え方", "sweep_line"),
    (152, "最近点対問題（幾何的アプローチ）", "closest_pair_geom"),
    (153, "ボロノイ図の基礎", "voronoi"),
    (154, "ドロネー三角形分割の基礎", "delaunay"),
    (155, "半平面交差", "halfplane_intersection"),
    (156, "計算幾何学の総合演習", "geom_comprehensive"),
    (157, "決定問題とクラスP", "decision_problems_p"),
    (158, "クラスNPと検証可能性", "class_np"),
    (159, "NP完全性の定義", "np_completeness"),
    (160, "帰着（リダクション）の考え方", "reductions"),
    (161, "SAT問題とクックの定理", "sat_cook"),
    (162, "巡回セールスマン問題のNP完全性", "tsp_np_complete"),
    (163, "頂点被覆問題・独立集合問題", "vertex_cover_independent"),
    (164, "近似アルゴリズムの考え方", "approximation"),
    (165, "PTAS（多項式時間近似スキーム）の直感", "ptas"),
    (166, "計算複雑性クラスの階層（PSPACE等）", "complexity_hierarchy"),
    (167, "乱択アルゴリズムの考え方", "randomized_algo"),
    (168, "モンテカルロ法とラスベガス法", "monte_carlo_las_vegas"),
    (169, "乱択クイックソートの解析", "randomized_quicksort"),
    (170, "スキップリストの確率的解析", "skip_list_analysis"),
    (171, "ハッシュ法における確率的解析", "hashing_analysis"),
    (172, "ブルームフィルタ", "bloom_filter"),
    (173, "オンラインアルゴリズムと競合比の考え方", "competitive_ratio"),
    (174, "ランダム化アルゴリズムの総合演習", "randomized_comprehensive"),
    (175, "並列計算モデルの基礎", "parallel_models"),
    (176, "並列ソートアルゴリズム", "parallel_sort"),
    (177, "分散アルゴリズムの基礎（リーダー選出）", "leader_election"),
    (178, "MapReduceの考え方", "mapreduce"),
    (179, "並列プレフィックス和", "parallel_prefix"),
    (180, "キャッシュ効率とアルゴリズム設計", "cache_efficient"),
    (181, "SIMDとアルゴリズムの高速化", "simd"),
    (182, "並列アルゴリズムの総合演習", "parallel_comprehensive"),
    (183, "k-means法（クラスタリング）", "kmeans"),
    (184, "k近傍法（k-NN）", "knn"),
    (185, "決定木アルゴリズムの基礎", "decision_trees"),
    (186, "勾配降下法の基礎", "gradient_descent"),
    (187, "線形回帰の最適化アルゴリズム", "linear_regression_opt"),
    (188, "主成分分析（PCA）の計算アルゴリズム", "pca"),
    (189, "ページランクアルゴリズム", "pagerank"),
    (190, "レコメンデーションアルゴリズムの基礎", "recommendation"),
    (191, "A/Bテストと多腕バンディット問題", "multiarmed_bandit"),
    (192, "ニューラルネットワークの誤差逆伝播法の基礎", "backpropagation"),
    (193, "競売アルゴリズムの基礎", "auction_algo"),
    (194, "ゲーム木探索（ミニマックス法）", "minimax"),
    (195, "アルファベータ枝刈り", "alpha_beta"),
    (196, "ナッシュ均衡と計算アルゴリズムの基礎", "nash_equilibrium"),
    (197, "アルゴリズム設計技法の比較まとめ", "design_techniques_review"),
    (198, "計算量のチートシート的総復習", "complexity_cheatsheet"),
    (199, "競技プログラミングにおけるアルゴリズム選択の指針", "competitive_programming_choice"),
    (200, "P対NP問題と今後のアルゴリズム研究の展望", "p_vs_np_outlook"),
]


def chapter_for(n: int, chapters: list[tuple[str, str, str, int, int]]) -> tuple[str, str, str]:
    for code, slug, title, lo, hi in chapters:
        if lo <= n <= hi:
            return code, slug, title
    raise KeyError(n)


def lesson_dir(code: str, chapter_slug: str, n: int, lesson_slug: str) -> str:
    return f"{code}_{chapter_slug}/{n:03d}_{lesson_slug}"


def validate() -> None:
    import re

    slug_re = re.compile(r"^[a-z][a-z0-9_]*$")
    for name, lessons, chapters in (
        ("math", MATH_LESSONS, MATH_CHAPTERS),
        ("algo", ALGO_LESSONS, ALGO_CHAPTERS),
    ):
        nums = [n for n, _, _ in lessons]
        assert nums == list(range(1, 201)), name
        slugs = [s for _, _, s in lessons]
        assert len(slugs) == len(set(slugs)), f"duplicate slug in {name}"
        for n, title, slug in lessons:
            assert slug_re.match(slug), (name, n, slug)
            assert len(slug) <= 32, (name, n, slug, len(slug))
            chapter_for(n, chapters)
        covered: set[int] = set()
        for _, _, _, lo, hi in chapters:
            covered.update(range(lo, hi + 1))
        assert covered == set(range(1, 201)), name
